### PR TITLE
Add command line script

### PR DESCRIPTION
**Pull request by chrisbaume**
This update adds a script for processing files directly from the command line. You can test locally by switching to  the `command-line` branch, navigating to the repo folder, and running  `pip3 install -e .` You should be able to run the command `voicefixer` from any directory.

### CODE REVIEW

**Comment by haoheliu** [comment]
Thanks Chris! Amazing feature! I'll add the cuda option on the command line and merge it afterwards.

**Comment by chrisbaume** [comment]
Oh yes, I forgot about the cuda option. I wonder if you could use [torch.cuda.is_available](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html) for the default?

**Comment by haoheliu** [comment]
Yes that make sense. Will do!

**Review by haoheliu — APPROVED** [review]
Looks good. Also rigorously tested.

**Comment by haoheliu** [comment]
Merged! 

Cheers,
Haohe

**Pull request merged**
